services:
  logger-service:
    build: .
    container_name: logger-asc-service
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PROJECT: logger-asc-service
      PLATFORM: nodejs
    volumes:
      - ./app.log:/app/app.log  # Logger writes here
      - ./app.log:/var/log/app.log  # Promtail reads here


  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    restart: unless-stopped
    ports:
      - "9080:9080"  # 🔥 Expose Promtail's HTTP API to the host
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml
      - ./app.log:/var/log/app.log  # Mount log file so Promtail can read it

  loki:
    image: grafana/loki:2.9.1
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:10.4.1
    container_name: grafana
    ports:
      - "80:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - loki
volumes:
  grafana-storage:
